env:
  browser: true
  es2021: true
settings:
  react:
    version: "detect"
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - plugin:promise/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module

plugins:
  - react
  - "@typescript-eslint"
  - import
  - promise

ignorePatterns: ["webpack.config.js", "cypress/**/*.js"]

globals:
  "cy": true
  "context": true
  "it": true
  "before": true
  "Cypress": true

rules:
  {
    "react/jsx-uses-react": "off",
    "react/react-in-jsx-scope": "off",
    "@typescript-eslint/adjacent-overload-signatures": "error",
    "@typescript-eslint/array-type": "error",
    "@typescript-eslint/ban-types": "error",
    "@typescript-eslint/consistent-type-assertions": "off",
    "@typescript-eslint/explicit-function-return-type":
      ["error", { "allowExpressions": true }],
    "@typescript-eslint/explicit-member-accessibility":
      ["error", { "overrides": { "constructors": "off" } }],
    "@typescript-eslint/indent":
      [
        "error",
        2,
        {
          "FunctionDeclaration": { "parameters": 2, "body": 1 },
          "FunctionExpression": { "parameters": 2, "body": 1 },
          "CallExpression": { "arguments": 1 },
          "SwitchCase": 1,
          "ObjectExpression": 1,
          "flatTernaryExpressions": true,
        },
      ],
    "@typescript-eslint/naming-convention":
      [
        "error",
        {
          "selector": "variableLike",
          "format": ["camelCase", "PascalCase", "UPPER_CASE"],
          leadingUnderscore: "allow",
        },
      ],
    "@typescript-eslint/no-empty-interface": "error",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-misused-new": "error",
    "@typescript-eslint/no-namespace": ["error", { "allowDeclarations": true }],
    "@typescript-eslint/no-non-null-assertion": "off",
    "@typescript-eslint/no-parameter-properties": "off",
    "@typescript-eslint/no-unused-vars":
      ["error", { "argsIgnorePattern": "^_", "varsIgnorePattern": "^_" }],
    "@typescript-eslint/no-var-requires": "off",
    "@typescript-eslint/prefer-for-of": "error",
    "@typescript-eslint/prefer-function-type": "error",
    "@typescript-eslint/triple-slash-reference":
      ["error", { "path": "never", "types": "prefer-import", "lib": "never" }],
    "@typescript-eslint/type-annotation-spacing": "error",
    "@typescript-eslint/unified-signatures": "error",
    "arrow-body-style": "error",
    "arrow-parens": ["error", "as-needed"],
    "camelcase": "off",
    "comma-dangle":
      [
        "error",
        {
          "arrays": "always-multiline",
          "objects": "always-multiline",
          "exports": "always-multiline",
          "imports": "always-multiline",
        },
      ],
    "comma-spacing": ["error", { "before": false, "after": true }],
    "complexity": "off",
    "constructor-super": "error",
    "curly": "error",
    "eol-last": ["error", "always"],
    "eqeqeq": ["error", "smart"],
    "guard-for-in": "error",
    "import/order":
      [
        "error",
        {
          "groups": ["builtin", "external", "internal"],
          "pathGroups":
            [{ "pattern": "react", "group": "external", "position": "before" }],
          "pathGroupsExcludedImportTypes": ["react"],
          "newlines-between": "always",
          "alphabetize": { "order": "asc", "caseInsensitive": true },
        },
      ],
    "indent": "off",
    "key-spacing": ["error", { "beforeColon": false, "afterColon": true }],
    "keyword-spacing": ["error", { "before": true, "after": true }],
    "max-classes-per-file": ["error", 1],
    "max-len": ["error", { "code": 120, "ignoreComments": true }],
    "new-parens": "error",
    "no-bitwise": "error",
    "no-caller": "error",
    "no-cond-assign": "error",
    "no-console":
      [
        "warn",
        {
          "allow":
            [
              "debug",
              "error",
              "info",
              "log",
              "time",
              "timeEnd",
              "trace",
              "warn",
            ],
        },
      ],
    "no-debugger": "error",
    "no-empty": "error",
    "no-empty-function": "error",
    "no-fallthrough": "error",
    "no-invalid-this": "off",
    "no-multi-spaces": 2,
    "no-multiple-empty-lines": "off",
    "no-new-wrappers": "error",
    "no-throw-literal": "error",
    "no-trailing-spaces": "error",
    "no-undef-init": "error",
    "no-unsafe-finally": "error",
    "no-unused-labels": "error",
    "no-var": "error",
    "object-curly-spacing": ["error", "always"],
    "object-shorthand": "error",
    "one-var": ["error", "never"],
    "padding-line-between-statements":
      [
        "error",
        { "blankLine": "always", "prev": "*", "next": "function" },
        { "blankLine": "always", "prev": "*", "next": "return" },
        { "blankLine": "always", "prev": "*", "next": "export" },
      ],
    "prefer-arrow-callback":
      ["error", { "allowNamedFunctions": true, "allowUnboundThis": true }],
    "prefer-const": "error",
    "quotes": ["error", "single"],
    "quote-props": ["error", "as-needed"],
    "radix": ["error", "always"],
    "semi": ["error", "always"],
    "semi-spacing": ["error", { "before": false, "after": true }],
    "sort-keys": "off",
    "space-before-blocks":
      [
        "error",
        { "functions": "always", "keywords": "always", "classes": "always" },
      ],
    "space-before-function-paren":
      [
        "error",
        { "anonymous": "always", "named": "never", "asyncArrow": "always" },
      ],
    "space-in-parens": ["error", "never"],
    "spaced-comment": ["error", "always", { "exceptions": ["-", "+"] }],
    "space-infix-ops": "error",
    "use-isnan": "error",
    "valid-typeof": "off",
  }

overrides:
  [
    {
      "files": ["*.tsx"],
      "rules":
        {
          "@typescript-eslint/explicit-function-return-type": "off",
          "@typescript-eslint/explicit-module-boundary-types": "off",
          "react/no-unescaped-entities": "off",
        },
    },
  ]
